#.travis.yml

language: node_js
node_js:
  - "10.16"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages
  - npm run test:headless
  - npm run lint

script:
  - npm run build:github-pages

after_success:
  - npm run deploy:github-pages


notifications:
  email:
    on_failure: ilse.haanstra@gmail.com
    on_success: ilse.haanstra@gmail.com
